OS2WEB-156: Removed profile dependency on loop_search
os2loop/profile pull request #151
Opened 2020-05-12 12:43 UTC by rimi-itk

https://jira.itkdev.dk/browse/OS2WEB-156

2020-05-20 08:05 UTC, martinyde requested changes

2020-05-20 08:05 UTC, martinyde commented on modules/loop_search_db/loop_search_db.module
> + * Implements hook_init().
Should this not follow the form? I.e only be loaded when the form is present? In a form alter perhaps?

2020-05-20 08:05 UTC, martinyde commented on modules/loop_search_db/loop-search-db--form.tpl.php
> +<?php if(0===1): ?>
I think this needs a comment with an explanation

2020-05-20 08:05 UTC, martinyde commented on modules/loop_search_db/loop_search_db.module
> +function loop_search_db_get_active_filters($facet) {
Missing function description

2020-05-25 08:54 UTC, rimi-itk commented on modules/loop_search_db/loop_search_db.module
> + * Implements hook_init().
Yes, you're absolutely right! I have to stop stealing code …

2020-05-25 08:54 UTC, rimi-itk commented on modules/loop_search_db/loop_search_db.module
> +function loop_search_db_get_active_filters($facet) {
Will fix.

2020-05-25 08:58 UTC, rimi-itk commented on modules/loop_search_db/loop-search-db--form.tpl.php
> +<?php if(0===1): ?>
Sorting of search results were still work in progress. It has now been added.

2020-05-26 07:39 UTC, martinyde approved these changes

2020-06-29 12:40 UTC, closed without merging