Feature search node
os2loop/profile pull request #49
Opened 2016-08-17 08:01 UTC by cableman

Support for search node in loop as an alternative to the current content search.

Project search node: https://github.com/search-node

2016-10-18 13:13 UTC, agger-magenta commented
OS2Loop-modulerne indeholder (overordnet set, og bortset fra det pull request, der gennemgås i dette review) en del afvigelser fra Drupal-kodestandarden og best practices i Drupal, hvilket blev afdækket ved brug af phpcs.
Afvigelserne fra kodestandarden vedrører især ting som antal blanke linjer, doc-strenge, antal blanke, indrykning af linjer med to spaces i stedet for fire, og så videre. Afvigelserne fra best practices vedrører variabler, der erklæres, men ikke bruges, samt navngivning af klasser og interfaces.
Hvis man ser bort fra fejl vedr. indrykning med to vs fire spaces, som det næppe er rimeligt at tælle som én fejl pr. linje, rapporterer phpcs om ca. 400 fejl på ca. 15.000 linjer PHP-kode, hvilket må siges at være forholdsvis lidt.
Da en undersøgelse af OS2Loops kode som helhed er udenfor scopet af dette review, anføres dette blot til information og som generel baggrund.

2016-10-18 13:21 UTC, agger-magenta commented
.inc-filerne i modules/loop_search_node/ skal placeres i mappen includes/. Det lader dog ikke til, at de andre moduler overholder dette. 
Filerne i modules/loop_search_node/js mangler modulnavnet i deres navne. loopResultController.js skulle for eksempel være loopResultController.loop_search_node.js

2016-10-18 13:37 UTC, agger-magenta reviewed
Der er stavefejl i nogle af kommentarerne, specifikt "Hanled" i stedet for "Handled" i linje 47 og 81.

2016-10-18 13:38 UTC, agger-magenta reviewed
Der angives ikke-oversættelige strenge.

Magiske tal anvendes uden kommentarer eller anden forklaring.

2016-10-18 13:47 UTC, agger-magenta reviewed
Gælder loop_search_node.install: Der er duplikeret kodestykker. Man kan overveje at faktorisere identisk kode til en funktion i stedet for blot at duplikere.

2016-10-18 13:50 UTC, agger-magenta reviewed
Gælder filen loop_search_node.features.inc:

I funktionen loop_search_node_default_search_api_index angives søge-API-indekset som et stort, konstant array. Eftersom nogle af disse indstillinger kan være noget, man kan være interesseret i at skrue på (for eksempel listen af stopwords på engelsk), hører de måske snarere hjemme i databasen eller en konfigurationsfil?

2016-10-18 13:57 UTC, agger-magenta commented
Dette er vores kodereview, som dækker hele dette pull request.
[code_review_os2_loop.pdf](https://github.com/os2loop/profile/files/536444/code_review_os2_loop.pdf)

2016-10-24 07:47 UTC, agger-magenta requested changes
OS2Loop-modulerne indeholder (overordnet set, og bortset fra det pull request, der gennemgås i dette review) en del afvigelser fra Drupal-kodestandarden og best practices i Drupal, hvilket blev afdækket ved brug af `phpcs`.

Afvigelserne fra kodestandarden vedrører især ting som antal blanke linjer, doc-strenge, antal blanke, indrykning af linjer med to spaces i stedet for fire, og så videre. Afvigelserne fra best practices vedrører variabler, der erklæres, men ikke bruges, samt navngivning af klasser og interfaces.

Hvis man ser bort fra fejl vedr. indrykning med to vs fire spaces, som det næppe er rimeligt at tælle som én fejl pr. linje, rapporterer `phpcs` om ca. 400 fejl på ca. 15.000 linjer PHP-kode, hvilket må siges at være forholdsvis lidt. Ikke desto mindre burde det dog rettes op.

Da en undersøgelse af OS2Loops kode som helhed er udenfor scopet af dette review, anføres dette blot til information og som generel baggrund.

KONKLUSION:

Koden er overordnet set velstruktureret og letlæselig.
Nogle steder kunne det, som anført, være rart med noget mere forklaring, især af "magiske tal". Selv om OS2Loops kodestandard tydeligvis tilstræbes at blive fulgt, følges den ikke konsekvent.

Umiddelbart er der tale om arbejde af høj kvalitet, ikke mindst hvis kommentarerne fra dette review indarbejdes i koden.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/loopResultController.js
> +          no_results_text: "Angiv værdi.",
Der angives ikke-oversættelige strenge.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/loopResultController.js
> +        jQuery.getScript(response.data.settings[0], function() {
Eksempel:
Drupal.settings.autocomplete_deluxe = response.data.settings[1].data.autocomplete_deluxe;

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/loopResultController.js
> +     * Hanled searching message, send when search is called.
Der er stavefejl i nogle af kommentarerne, specifikt "Hanled" i stedet for "Handled" i linje 47 og 81.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/loopResultController.js
> +     * Hanled search results hits from the search box application.
Der er stavefejl i nogle af kommentarerne, specifikt "Hanled" i stedet for "Handled" i linje 47 og 81.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/loop_search_node.install
> +  db_update('block')
Der er duplikeret kodestykker, f.eks. her. Man kan overveje at faktorisere identisk kode til en funktion i stedet for blot at duplikere.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/loop_search_node.pages_default.inc
> +}
Der bruges magiske tal uden kommentar eller anden forklaring.
Eksempel:

`
$display->content['new-72f9dfde-740c-4391-a75e-39e8535a83c3'] = $pane;`

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/loop_search_node.features.inc
> +  $items = array();
I denne funktion angives søge-API-indekset som et stort, konstant array. Eftersom nogle af disse indstillinger kan være noget, man kan være interesseret i at skrue på (for eksempel listen af stopwords på engelsk), hører de måske snarere hjemme i databasen eller en konfigurationsfil?

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/angular-locale_da-dk.js
> +function getVF(n, opt_precision) {
Det kunne være rart med en kommentar til forklaring af, hvad funktionerne getVF og getWT gør, og specielt hvorfor de gør det.

2016-10-24 07:47 UTC, agger-magenta commented on modules/loop_search_node/js/loopSearchBoxController.js
> +        //// Get state from previous search.
Linjerne 49-82 er udkommenteret. Den udkommenterede kode bør måske slettes helt, hvis der ikke kan findes en løsning på den problematik, der beskrives i TODO-kommentaren. Eller er den anførte reload (linje 47) løsningen?
I alle tilfælde bør det ikke være nødvendigt (og er i hvert fald ikke god stil) at kopiere koden fra init()-funktionen længere nede.

2016-10-24 07:47 UTC, agger-magenta commented on themes/loop/css/styles.css
> +    *behavior: url(url("../lib/boxsizing.htc"));
url() kaldes to gange flere steder. Er dette meningen? 
Eksempel:
`
*behavior: url(url("../lib/boxsizing.htc"));
`

2016-10-24 07:47 UTC, agger-magenta commented on themes/loop/templates/search/angular/result.html
> +    <p>Hvis du tror, at dit spørgsmål ikke stillet før med anden ordlyd, kan du oprette spørgsmålet ved hjælp af nedenstående skema. Du kan også ændre din søgning og søge igen.</p>
Der angives ikke-oversættelige strenge. Eksempel:

`
<p>Hvis du tror, at dit spørgsmål ikke stillet før med anden ordlyd,
kan du oprette spørgsmålet ved hjælp af nedenstående skema. Du kan også ændre
din søgning og søge igen.</p>`

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/angular-locale_da-dk.js
> +function getVF(n, opt_precision) {
This is in the AngularJS code (https://docs.angularjs.org/guide/i18n -> https://code.angularjs.org/1.5.8/i18n/angular-locale_da-dk.js). It ensures that the date's etc. it correctly displayed.

It's not a file we want to make changes in.

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/loopResultController.js
> +     * Hanled search results hits from the search box application.
Fixed :-)

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/loopResultController.js
> +     * Hanled searching message, send when search is called.
Fixed

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/loopResultController.js
> +        jQuery.getScript(response.data.settings[0], function() {
Not sure what to do here ?

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/loopSearchBoxController.js
> +        //// Get state from previous search.
The reload is the only current solution, so removed the dead code.

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/loop_search_node.features.inc
> +  $items = array();
This is part of a feature export of the basic configuration. So it's how panels and features work in Drupal.

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/loop_search_node.install
> +  db_update('block')
Simply remove the not need update functions. This was used on the upgrade site in connection with customers tests.

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/loop_search_node.pages_default.inc
> +}
That's panels internal id. This is how features and panels works in Drupal.

2016-10-31 13:34 UTC, cableman commented on themes/loop/css/styles.css
> +    *behavior: url(url("../lib/boxsizing.htc"));
It's should not be inside a url, but the issue is in the compilation of sass to css and the current setup for the theme don't work in node 4.x, 5.x of 6.x... So this is outside the scope of this PR.

If it needs to be fixed I think the way to go is creating an support ticket to loop on getting this fixed... I would expect this to take from 1-2 hours as some of the sass may need to be re-written to use the current versions.

2016-10-31 13:34 UTC, cableman commented on themes/loop/templates/search/angular/result.html
> +    <p>Hvis du tror, at dit spørgsmål ikke stillet før med anden ordlyd, kan du oprette spørgsmålet ved hjælp af nedenstående skema. Du kan også ændre din søgning og søge igen.</p>
They have are now wrapped in translation functions in English.

2016-10-31 13:34 UTC, cableman commented on modules/loop_search_node/js/loopResultController.js
> +          no_results_text: "Angiv værdi.",
Translation wrappers applied now :-)

2016-11-01 09:56 UTC, agger-magenta commented on modules/loop_search_node/loop_search_node.pages_default.inc
> +}
Fine! Even our in-house Drupal developer thought it might be nice with a comment, though.

2016-11-01 09:57 UTC, agger-magenta commented on modules/loop_search_node/loop_search_node.features.inc
> +  $items = array();
OK.

2016-11-01 10:01 UTC, agger-magenta commented on modules/loop_search_node/js/angular-locale_da-dk.js
> +function getVF(n, opt_precision) {
OK, I thought it was a local customization. It is debatable whether a single module's JS directory is the correct location for a general-purpose third party module.

2016-11-01 10:01 UTC, agger-magenta commented on themes/loop/css/styles.css
> +    *behavior: url(url("../lib/boxsizing.htc"));
OK.

2016-11-04 12:38 UTC, agger-magenta approved these changes

2016-11-08 11:25 UTC, magnify commented on modules/loop_search_node/loop_search_node.pages_default.inc
> +}
We can't comment on features exported code, as it will be overridden next time it is exported.

2016-11-08 11:26 UTC, magnify commented
Is the PR approved? If so please merge it. :)

2016-11-10 12:22 UTC, agger-magenta approved these changes

2016-11-21 12:12 UTC, merged