UNI•Login
os2loop/profile pull request #52
Opened 2016-10-20 15:18 UTC by rimi-itk

* Adds a new UNI•Login module for getting use data from UNI•Login web service after succesful login.
* Changes the login form to let the user choose among the login services configured on the site.

2016-11-09 09:34 UTC, agger-magenta requested changes

2016-11-09 09:34 UTC, agger-magenta commented on modules/loop_unilogin/loop_unilogin.module
> +    $info = unilogin_services_w02_load($unilogin_id, array('hentPerson'));
Det kunne være rart med nogle flere kommentarer her for at forklare, hvad der foregår.

2016-11-09 09:34 UTC, agger-magenta commented on themes/loop/template.php
> +  if (function_exists('saml_sp__load_all_idps')) {
According to the OS2Loop guidelines "modules which alter or extend functionality provided by the project core modules should use appropriate alter hooks to override these instead of forking these modules". 

That would tend to imply that the SAML login should perhaps not be moved but should stay in the `loop_saml` module. Does this change introduce any kind of backwards incompatibility and if so, how should they be handled?

2016-11-09 14:09 UTC, rimi-itk commented on modules/loop_unilogin/loop_unilogin.module
> +    $info = unilogin_services_w02_load($unilogin_id, array('hentPerson'));
I've added a couple of clarifying comments.

2016-11-09 14:12 UTC, rimi-itk commented on themes/loop/template.php
> +  if (function_exists('saml_sp__load_all_idps')) {
I'm not changing or moving anything, but simply building a list of active login services to be rendered in the login template. I've added some comments to make it more clear what is going on.

2016-11-10 12:21 UTC, agger-magenta approved these changes

2016-11-10 12:22 UTC, merged